@extends('backend.layouts.app')
@php
    $editable = $editable && (auth()->user()->user_type === 'admin' || in_array('edit_salary_sheet', $_authPermissions));
@endphp
@section('content')
    <div class="card">
        <div class="card-header row gutters-5 align-items-end">
            <div class="col mb-2 mb-md-0">
                <h5 class="mb-md-0 h6">Monthly Salary Sheet</h5>
                <small class="text-muted">Generate salary from attendance and update overtime, late fee, and bonuses.</small>
            </div>

            <div class="col-md-2 mb-2 mb-md-0">
                <input type="month" name="month" id="salary-month" class="form-control form-control-sm"
                    value="{{ request('month', now()->subMonth()->format('Y-m')) }}" max="{{ now()->subMonth()->format('Y-m') }}">
            </div>

            <div class="col-auto">
                <button type="button" class="btn btn-primary btn-sm" @if($editable) id="btn-generate-sheet" @else disabled @endif>
                    <i class="las la-sync"></i> Generate
                </button>
            </div>

            <div class="col-auto">
                <button type="button" class="btn btn-success btn-sm" @if($editable) id="btn-save-sheet" @else disabled @endif>
                    <i class="las la-save"></i> Save Adjustments
                </button>
            </div>

            <div class="col-auto">
                <button type="button" class="btn btn-info btn-sm" id="btn-export-sheet">
                    <i class="las la-file-excel"></i> Export
                </button>
            </div>
        </div>

        <div class="card-body">
            @if($sheet)
                <div class="alert alert-info">
                    <i class="las la-info-circle"></i> Generated By <strong>{{ data_get($sheet, 'generated_by', 'System') }}</strong>
                    @if(data_get($sheet, 'generated_at', null))
                    on <strong>{{ \Carbon\Carbon::parse(data_get($sheet, 'generated_at'))->format('Y-m-d h:i a') }}</strong>
                    @endif
                    @if(data_get($sheet, 'updated_at', null))
                    . Last updated on <strong>{{ \Carbon\Carbon::parse(data_get($sheet, 'updated_at'))->format('Y-m-d h:i a') }}</strong>.
                    @endif
                </div>
            @endif
            <div id="salary-summary-wrapper" class="mb-3">
                @include('backend.salary_sheets.partials.summary', ['summary' => $summary])
            </div>

            <div id="salary-sheet-table-wrapper">
                @include('backend.salary_sheets.partials.table', ['sheet' => $sheet, 'editable' => $editable])
            </div>
        </div>
    </div>
@endsection

@section('modal')
    <div class="modal fade" id="bonusModal" tabindex="-1" role="dialog" aria-labelledby="bonusModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="bonusModalLabel">Add Bonus</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="staff_id" id="bonus-staff-id">
                    <div class="form-group">
                        <label for="bonus-title">Title</label>
                        <input type="text" class="form-control form-control-sm" id="bonus-title" placeholder="Bonus title">
                        <small class="text-danger bonus-form-error" id="bonus-title-error"></small>
                    </div>
                    <div class="form-group">
                        <label for="bonus-amount">Amount</label>
                        <input type="number" min="0" step="1" class="form-control form-control-sm" id="bonus-amount" placeholder="Bonus amount">
                        <small class="text-danger bonus-form-error" id="bonus-amount-error"></small>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-sm btn-primary" id="save-bonus-btn">Save changes</button>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        (function() {
            const editable = {{ $editable ? 'true' : 'false' }};

            function selectedPayload() {
                return {
                    month: $('#salary-month').val(),
                };
            }

            function adjustmentPayload() {
                const payload = {
                    id: '{{ data_get($sheet, "id") }}',
                    month: $('#salary-month').val(),
                    adjustments: {}
                };

                $('#salary-sheet-table tbody tr').each(function () {
                    const $row = $(this);
                    const staffId = $row.data('staff-id');

                    if (!staffId) return;

                    // Initialize staff object
                    payload.adjustments[staffId] = {
                        overtime_amount: parseFloat($row.find('.overtime-amount').val()) || 0,
                        late_fee_amount: parseFloat($row.find('.late-fee-amount').val()) || 0,
                        leave_amount: parseFloat($row.find('.leave-amount').val()) || 0,
                        adjustment_amount: parseFloat($row.find('.adjustment-amount').val()) || 0,
                        bonuses: []
                    };

                    // Collect bonuses
                    $row.find('.bonus-item').each(function () {
                        const $bonus = $(this);

                        const title = $bonus.find('.bonus-title').val() || '';
                        const amount = parseFloat($bonus.find('.bonus-amount').val()) || 0;

                        // Ignore empty bonus rows
                        if (title || amount > 0) {
                            payload.adjustments[staffId].bonuses.push({
                                title: title,
                                amount: amount
                            });
                        }
                    });
                });

                return payload;
            }

            function bonusRowTemplate(bonus) {
                return `
                    <div class="bonus-item border p-2 mb-2 rounded d-flex justify-content-between align-items-center">
                        <input type="hidden" name="adjustments['${bonus.staff_id}'][bonuses][][title]" class="bonus-title" value="${bonus.title || ''}">
                        <input type="hidden" name="adjustments['${bonus.staff_id}'][bonuses][][amount]" class="bonus-amount" value="${bonus.amount || ''}">
                        <span class="fs-11 fs-md-12">${bonus.title || 'Bonus'}: ${bonus.amount || 0}</span>
                        <button type="button" class="btn btn-soft-danger btn-sm remove-bonus-row fs-8 fs-md-10 px-1 px-md-2 py-1" title="Remove Bonus">
                            <i class="las la-times"></i>
                        </button>
                    </div>
                `;
            }

            function setLoading($btn, isLoading, text) {
                if (isLoading) {
                    $btn.data('old-html', $btn.html());
                    $btn.prop('disabled', true).html(
                        `<span class="spinner-border spinner-border-sm mr-1"></span>${text}`);
                } else {
                    $btn.prop('disabled', false).html($btn.data('old-html'));
                }
            }

            function renderResponse(data) {
                $('#salary-sheet-table-wrapper').html(data.html);
                $('#salary-summary-wrapper').html(data.summary_html);
                AIZ.plugins.bootstrapSelect('refresh');
                AIZ.plugins.fooTable();
            }

            function updateSalaryAmounts(staffId) {
                const $row = $(`tr[data-staff-id="${staffId}"]`);
                const overtimeAmount = parseFloat($row.find('.overtime-amount').val() || 0);
                const lateFeeAmount = parseFloat($row.find('.late-fee-amount').val() || 0);
                const adjustmentAmount = parseFloat($row.find('.adjustment-amount').val() || 0);
                const leaveAmount = parseFloat($row.find('.leave-amount').val() || 0);
                $row.find('.text-leave-amount').text(leaveAmount.toFixed(2));
                let bonusTotal = 0;

                $row.find('.bonus-list .bonus-item').each(function() {
                    const amount = parseFloat($(this).find('.bonus-amount').val() || 0);
                    bonusTotal += amount;
                });

                const basicSalary = parseFloat($row.find('.basic-salary-amount').text() || 0);
                const grossSalary = basicSalary + overtimeAmount + bonusTotal;
                const netSalary = grossSalary + adjustmentAmount - lateFeeAmount - leaveAmount; // Adjust if there are other deductions

                $row.find('.bonus-total-amount').text(bonusTotal.toFixed(2));
                $row.find('.gross-salary-amount').text(grossSalary.toFixed(2));
                $row.find('.net-salary-amount').text(netSalary.toFixed(2));
            }

            function resetBonusForm() {
                $('.bonus-form-error').text('');
                $('#bonus-staff-id').val('');
                $('#bonus-title').val('');
                $('#bonus-amount').val('');
            }

            $('#salary-month').on('change', function() {
                const month = $('#salary-month').val();
                if (month) {
                    window.location.href = `?month=${month}`;
                }
            });

            $(document).on('input', '.overtime-amount, .late-fee-amount, .adjustment-amount, .leave-amount', function() {
                const staffId = $(this).closest('tr').data('staff-id');
                updateSalaryAmounts(staffId);
            });

            $(document).on('click', '.add-bonus-row', function() {
                resetBonusForm();
                const staffId = $(this).closest('tr').data('staff-id');
                $('#bonus-staff-id').val(staffId);

                $('#bonusModal').modal('show');

                $('#bonus-title').focus();
            });

            $(document).on('click', '#save-bonus-btn', function() {
                const bonus = {
                    title: $('#bonus-title').val().trim(),
                    amount: parseFloat($('#bonus-amount').val()),
                    staff_id: $('#bonus-staff-id').val()
                };

                if (!bonus.title) {
                    $('#bonus-title-error').text('Bonus title is required.');
                    return;
                }else {
                    $('#bonus-title-error').text('');
                }

                if (isNaN(bonus.amount) || bonus.amount <= 0) {
                    $('#bonus-amount-error').text('Please enter a valid amount for the bonus.');
                    return;
                }else{
                    $('#bonus-amount-error').text('');
                }

                const $bonusList = $(`tr[data-staff-id="${bonus.staff_id}"] .bonus-list`);
                const bonusItems = $bonusList.find('.bonus-item');
                if (bonusItems.length == 0) {
                    $bonusList.empty();
                }
                $bonusList.append(bonusRowTemplate(bonus));
                $('#bonusModal').modal('hide');

                updateSalaryAmounts(bonus.staff_id);
            });

            $(document).on('click', '.remove-bonus-row', function() {
                const staffId = $(this).closest('tr').data('staff-id');
                $(this).closest('.bonus-item').remove();

                const $bonusList = $(`tr[data-staff-id="${staffId}"] .bonus-list`);
                const bonusItems = $bonusList.find('.bonus-item');
                if (bonusItems.length == 0) {
                    $bonusList.append('<div class="text-center small text-muted mb-2">No bonus added.</div>');
                }

                updateSalaryAmounts(staffId);
            });

            $('#btn-generate-sheet').on('click', function() {
                if (!editable) {
                    showAlert('error', 'You cannot generate salary sheet for this month as it is not editable.');
                    return;
                }
                Swal.fire({
                    title: 'Generate Salary Sheet',
                    text: 'Are you sure you want to generate the salary sheet for the selected month? This will overwrite any existing or unsaved adjustments.',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonText: 'Yes, Generate',
                    cancelButtonText: 'Cancel'
                }).then((result) => {
                    if (result.isConfirmed) {
                        const $btn = $(this);
                        setLoading($btn, true, 'Generating...');

                        $.ajax({
                            url: '{{ route('salary.sheet.generate') }}',
                            method: 'GET',
                            data: selectedPayload(),
                            success: function(response) {
                                if (response.success) {
                                    showAlert('success', response.message || 'Request submitted.');
                                } else {
                                    showAlert('error', response.message || 'Failed to generate salary sheet.');
                                }
                            },
                            error: function(xhr) {
                                const message = xhr.responseJSON?.message || 'Request Failed. Please try again.';
                                showAlert('error', message);
                            },
                            complete: function() {
                                setLoading($btn, false);
                            }
                        });
                    }
                });
            });

            $('#btn-save-sheet').on('click', function() {
                if (!editable) {
                    showAlert('error', 'Salary sheet for this month is not editable.');
                    return;
                }

                const payload = adjustmentPayload();
                if (!payload.id) {
                    showAlert('error', 'No salary sheet found to update. Please generate the salary sheet first.');
                    return;
                }
                const $btn = $(this);
                setLoading($btn, true, 'Saving...');

                $.ajax({
                    url: '{{ route('salary.sheet.update') }}',
                    method: 'POST',
                    data: payload,
                    headers: {
                        'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    },
                    success: function(response) {
                        if (response.success) {
                            showAlert('success', response.message || 'Salary sheet updated successfully.');
                            renderResponse(response);
                        } else {
                            showAlert('error', response.message || 'Failed to update salary sheet.');
                        }
                    },
                    error: function(xhr) {
                        const message = xhr.responseJSON?.message || 'Request Failed. Please try again.';
                        showAlert('error', message);
                    },
                    complete: function() {
                        setLoading($btn, false);
                    }
                });
            });

            $('#btn-export-sheet').on('click', function() {
                let url = new URL(window.location.href);
                url.searchParams.set('export', '1');
                window.open(url.toString(), '_blank');
            });
        })();
    </script>
@endsection
